#!/bin/bash

# Check if all required parameters are passed
if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# Use scp to transfer the file to the server
scp -i "$path_to_ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip:~/"

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
  echo "File transfer successful!"
else
  echo "File transfer failed. Please check the parameters and try again."
fi
