#!/usr/bin/env bash

# Update apt package index
sudo apt-get update

# Install nginx package with -y flag
sudo apt-get install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/80 default_server/80/g' /etc/nginx/sites-available/default

# Start nginx
sudo service nginx start

# Check if nginx is running
sudo service nginx status > /dev/null 2>&1

# Create HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html
