#!/usr/bin/env bash

# Install Nginx if not already installed
if [ $(dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  apt-get update
  apt-get install -y nginx
fi

# Configure the Nginx server to redirect /redirect_me
FILE=/etc/nginx/sites-available/default
if grep -q "location /redirect_me" "$FILE"; then
  sed -i "/location \/redirect_me/,/}/d" "$FILE"
fi

echo "server {
    listen 80;
    listen [::]:80;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # ... other configurations ...
}" >> "$FILE"

# Restart Nginx to apply the changes
service nginx restart
